#conding=utf-8




class_column=[

 'gender'
, 'age'
, 'app_down_src'
, 'reg_tname_intrv'
, 'tname_apply_intrv'
, 'pass_limit_intrv'
, 'reg_apply_intrv'
, 'market_channel'
, 'activ_chan_src'
, 'rgst_src'
, 'limit_appl_cnt'
, 'crdt_sum_lim'
, 'supr_edu_dip'
, 'invt_rgst_succ_pers'
, 'long_pos_loan_ind'
, 'id_province'
, 'unicon'
, 'last_login_to_now'
, 'idcard_time_to_now'
, 'last_app_version'
, 'push_permission'
, 'phone_number_permission'
, 'album_permission'
, 'id_degree'
, 'id_area'
, 'domicile_degree'
, 'domicile_area'
, 'use_card_record'
, 'card_overdue_record'
, 'loan_acct_sts_zhengchang'
, 'loan_acct_sts_jieqing'
, 'loan_acct_sts_yuqi'
, 'loan_acct_sts_daizhang'
, 'loan_type_xiaofei'
, 'loan_type_nonghu'
, 'loan_type_qiche'
, 'loan_type_shangyong'
, 'loan_type_zhufang'
, 'loan_type_gongjijin'
, 'loan_type_qita'
, 'loan_type_zhuxue'
, 'loan_type_jingying'
, 'first_loan_card_open_month'
, 'first_loan_open_month'
, 'is_long_loan_qh'
, 'is_long_loan_rh'
, 'divece_count'
, 'ave_app_time'
, 'ave_app_times'
, 'used_time'
, 'p2p_ap_count'
, 'p2p_ap_rate'
, 'finance_count_in_mes'
, 'finance_count_in_mes_rate'
, 'cont_amt'
, 'maprice_rate'
, 'com_kind_cd'
, 'ever_indtry_sal_cd'
, 'duty_cde'
, 'profsn_cd'
, 'residence_type_cde'
, 'other_loan_count'
, 'loan_card_count'
, 'unover_loan_acct_count'
, 'unover_loan_credit_limit'
, 'unover_loan_balance'
, 'loan_five_over_record'
, 'loan_over_count'
, 'loan_over_maxduration'
, 'unover_card_acct_count'
, 'unover_card_credit_limit'
, 'unover_card_used_credit_limit'
, 'unover_card_latest_6month_usedavg_amount'
, 'card_over_count'
, 'gr_1'
, 'gr_2'
, 'gr_3'
, 'gr_twoy_1'
, 'gr_twoy_2'
, 'gr_twoy_3'
, 'house_loan_count'
, 'loan_pbc_gl_count'
, 'loan_creditlimitamount_amount'
, 'loan_balance'
, 'card_curroverduecyc'
, 'card_usedcreditlimitamount'
, 'card_latest6monthusedavgamount'
, 'card_curroverdueamount'
, 'card_all_count'
, 'card_acct_sts_daizhang'
, 'card_acct_sts_dongjie'
, 'loan_class5stat_keyi'
, 'loan_class5state_ciji'
, 'loan_class5state_guanzhu'
, 'amount'
, 'bnk_amount'
, 'cnss_amount'
, 'p2p_amount'
, 'query_amt'
, 'query_amtm3'
, 'query_amtm6'
, 'td_count'
, 'td_score'
, 'td_in_use_time'
, 'marrg_situ'
, 'check_monthly_ry_1week'
, 'debit_one_detl_page_cnt_1week'
, 'debit_one_page_cnt_1week'
, 'indiv_loan_cont_cnt_1week'
, 'check_monthly_ry_1moon'
, 'debit_one_detl_page_cnt_1moon'
, 'debit_one_page_cnt_1moon'
, 'indiv_loan_cont_cnt_1moon'
, 'check_monthly_ry_3moon'
, 'debit_one_detl_page_cnt_3moon'
, 'debit_one_page_cnt_3moon'
, 'indiv_loan_cont_cnt_3moon'
, 'actv_lmt_back_ind_start_up_app'
,'lmt_actv_back_first_tm_start_up_app_tm_intrv'
,'categrocial']


reg_column=[
'app_down_src'
,'tname_intrv'
,'gender'
,'age'
,'pass_limit_intrv'
,'market_channel'
,'activ_chan_src'
,'rgst_src'
,'limit_appl_cnt'
,'crdt_sum_lim'
,'supr_edu_dip'
,'marrg_situ'
,'pres_house_char'
,'long_pos_loan_ind'
,'live_province'
,'indtry_sal_cd'
,'push_permission'
,'phone_number_permission'
,'album_permission'
,'id_degree'
,'id_area'
,'domicile_degree'
,'domicile_area'
,'use_card_record'
,'card_overdue_record'
,'loan_acct_sts_zhengchang'
,'loan_acct_sts_jieqing'
,'loan_acct_sts_yuqi'
,'loan_acct_sts_daizhang'
,'loan_type_xiaofei'
,'loan_type_nonghu'
,'loan_type_qiche'
,'loan_type_shangyong'
,'loan_type_zhufang'
,'loan_type_gongjijin'
,'loan_type_qita'
,'loan_type_zhuxue'
,'loan_type_jingying'
,'first_loan_card_open_month'
,'first_loan_open_month'
,'is_long_loan_qh'
,'is_long_loan_rh'
,'p2p_ap_count'
,'p2p_ap_rate'
,'finance_count_in_mes'
,'finance_count_in_mes_rate'
,'cont_amt'
,'maprice_rate'
,'com_kind_cd'
,'ever_indtry_sal_cd'
,'duty_cde'
,'profsn_cd'
,'residence_type_cde'
,'other_loan_count'
,'loan_card_count'
,'unover_loan_acct_count'
,'unover_loan_credit_limit'
,'unover_loan_balance'
,'unover_loan_latest_6month_usedavg_amount'
,'loan_curr_overdue_amount'
,'loan_five_over_record'
,'loan_over_count'
,'loan_over_maxduration'
,'unover_card_acct_count'
,'unover_card_credit_limit'
,'unover_card_used_credit_limit'
,'unover_card_latest_6month_usedavg_amount'
,'card_over_count'
,'gr_1'
,'gr_2'
,'gr_3'
,'gr_twoy_1'
,'gr_twoy_2'
,'gr_twoy_3'
,'house_loan_count'
,'loan_pbc_gl_count'
,'loan_creditlimitamount_amount'
,'loan_balance'
,'card_curroverduecyc'
,'card_usedcreditlimitamount'
,'card_latest6monthusedavgamount'
,'card_curroverdueamount'
,'card_all_count'
,'card_acct_sts_daizhang'
,'card_acct_sts_dongjie'
,'loan_class5stat_keyi'
,'loan_class5state_ciji'
,'loan_class5state_guanzhu'
,'qh_amount'
,'qh_bnk_amount'
,'qh_cnss_amount'
,'qh_p2p_amount'
,'td_count'
,'td_score'
,'regress']